apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: res-ray-test
  region: us-east-1
  version: "latest"
managedNodeGroups:
  - name: nodegroup-custom-aviary-latest-ami-up-cpu
    #the thing i built
    ami: ami-02b10b22644305b25
    instanceType: m5.2xlarge
    amiFamily: AmazonLinux2
    desiredCapacity: 1
    minSize: 1
    maxSize: 6
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh res-ray-test --container-runtime containerd

#eksctl create nodegroup -f nodegroup-custom-aviary-ami.yaml
#i create a test-ami EC2 instance to check the AMI. i can log into it at least
