apiVersion: v1
kind: Pod
metadata:
  name: monolith
spec:
  containers:
    - name: monolith
      image: IMAGE
      imagePullPolicy: Always
      command:
        ["python", "/app/cli.py", "kafka", "consume", "-t", "test.order_status"]
      envFrom:
        - configMapRef:
            name: res-data-env
  restartPolicy: OnFailure
